### ISSUE TITLE
Build fails due to missing exported member

### ISSUE THREAD

**Issue by sheinze** [OI4/oi4-oec-demo#8]
<img width="1071" alt="grafik" src="https://github.com/OI4/oi4-oec-demo/assets/7068676/ee8c10b7-0ac3-4bdf-bedc-4ed44d93c670">

Branch: development
System: M1 mbp 16GB, maOS 13.4 Ventura

**Comment by Weinschenk** [comment]
@sheinze please verify if the bug is solved with the latest merges
